#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGAdminUserUpdateDto
@end

@interface AGAdminUserUpdateDto : AGObject

/* 用户名 [optional]
 */
@property(nonatomic) NSString* username;
/* 手机号 [optional]
 */
@property(nonatomic) NSString* phone;
/* 角色 (USER / ADMIN) [optional]
 */
@property(nonatomic) NSString* role;
/* 全名 [optional]
 */
@property(nonatomic) NSString* fullName;
/* 头像URL [optional]
 */
@property(nonatomic) NSString* avatarUrl;
/* 个人简介 [optional]
 */
@property(nonatomic) NSString* bio;
/* 地理位置 [optional]
 */
@property(nonatomic) NSString* location;
/* 关注的农作物列表 [optional]
 */
@property(nonatomic) NSArray<NSString*>* followedCrops;

@end
