#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGAdminMessage
@end

@interface AGAdminMessage : AGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* type;

@property(nonatomic) NSString* title;

@property(nonatomic) NSString* content;

@property(nonatomic) NSString* targetLocation;

@property(nonatomic) NSString* targetCrops;

@property(nonatomic) NSDate* createdAt;

@end
