#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGAdminMessageCreateRequest
@end

@interface AGAdminMessageCreateRequest : AGObject

/* 消息类型：SYSTEM (全员系统消息), ALERT (定向预警消息) 
 */
@property(nonatomic) NSString* type;
/* 消息标题 
 */
@property(nonatomic) NSString* title;
/* 消息内容 
 */
@property(nonatomic) NSString* content;
/* 定向作物偏好 (仅ALERT类型有效，不填则发给所有地区匹配的用户) [optional]
 */
@property(nonatomic) NSArray<NSString*>* targetCrops;
/* 定向地理位置 (仅ALERT类型有效，不填则发给所有作物匹配的用户) [optional]
 */
@property(nonatomic) NSString* targetLocation;

@end
