#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGAgentChatHistory
@end

@interface AGAgentChatHistory : AGObject

/* 主键ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* 用户ID [optional]
 */
@property(nonatomic) NSNumber* userId;
/* 用户提问文本 [optional]
 */
@property(nonatomic) NSString* userQuery;
/* 图片地址或Base64(截断) [optional]
 */
@property(nonatomic) NSString* imageUrl;
/* Agent返回的诊断结果 [optional]
 */
@property(nonatomic) NSString* agentResponse;
/* 创建时间 [optional]
 */
@property(nonatomic) NSDate* createTime;

@end
