#import <Foundation/Foundation.h>
#import "AGAdminMessageCreateRequest.h"
#import "AGAdminUserUpdateDto.h"
#import "AGChangePhoneRequest.h"
#import "AGChatRequest.h"
#import "AGCommentRequest.h"
#import "AGLoginRequest.h"
#import "AGMultipartUploadCompleteRequest.h"
#import "AGMultipartUploadInitRequest.h"
#import "AGMyCropCreateRequest.h"
#import "AGMyCropUpdateRequest.h"
#import "AGPostCreateRequest.h"
#import "AGProfileUpdateRequest.h"
#import "AGRefreshTokenRequest.h"
#import "AGRegisterRequest.h"
#import "AGResultAdminUserResponseDto.h"
#import "AGResultAuthResponse.h"
#import "AGResultChatProfileResponse.h"
#import "AGResultCommentResponseDto.h"
#import "AGResultListAgentChatHistory.h"
#import "AGResultListDiagnosisItem.h"
#import "AGResultListMyCropResponseDto.h"
#import "AGResultListString.h"
#import "AGResultListTagDto.h"
#import "AGResultLong.h"
#import "AGResultMessageGroupResponseDto.h"
#import "AGResultMultipartUploadInitResponse.h"
#import "AGResultMyCropResponseDto.h"
#import "AGResultObject.h"
#import "AGResultPageResultAdminMessage.h"
#import "AGResultPageResultAdminUserResponseDto.h"
#import "AGResultPageResultCommentResponseDto.h"
#import "AGResultPageResultMessageResponseDto.h"
#import "AGResultPageResultPostResponseDto.h"
#import "AGResultPostResponseDto.h"
#import "AGResultSearchResultResponse.h"
#import "AGResultString.h"
#import "AGResultUserProfileDto.h"
#import "AGResultVoid.h"
#import "AGSendSmsRequest.h"
#import "AGSmsLoginRequest.h"
#import "AGSseEmitter.h"
#import "AGTagOperationRequest.h"
#import "AGApi.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface AGApiService: NSObject <AGApi>

extern NSString* kAGApiServiceErrorDomain;
extern NSInteger kAGApiServiceMissingParamErrorCode;

-(id) initWithApiClient:(AGApiClient *)apiClient ;

/// 发表评论
/// 
///
/// @param _id 
/// @param commentRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultCommentResponseDto*
-(NSURLSessionTask*) addCommentWithId: (NSNumber*) _id
    commentRequest: (AGCommentRequest*) commentRequest
    completionHandler: (void (^)(AGResultCommentResponseDto* output, NSError* error)) handler;


/// 添加种植标签 (浇水、施肥、用药、笔记)
/// 
///
/// @param _id 
/// @param tagOperationRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) addTagWithId: (NSNumber*) _id
    tagOperationRequest: (AGTagOperationRequest*) tagOperationRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 用户注册
/// 提供用户名、手机号和密码进行注册，注册成功后自动下发 JWT Token
///
/// @param registerRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) callRegisterWithRegisterRequest: (AGRegisterRequest*) registerRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 换绑手机号
/// 
///
/// @param changePhoneRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) changePhoneWithChangePhoneRequest: (AGChangePhoneRequest*) changePhoneRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 发起多模态诊断请求
/// 上传文本描述和可选的图片，结合地理位置与天气数据返回结构化诊断结果。
///
/// @param chatRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultListDiagnosisItem*
-(NSURLSessionTask*) chatWithChatRequest: (AGChatRequest*) chatRequest
    completionHandler: (void (^)(AGResultListDiagnosisItem* output, NSError* error)) handler;


/// 发起多模态诊断请求(带耗时剖析)
/// 返回诊断结果并附带服务端分段耗时，用于定位慢点。
///
/// @param chatRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultChatProfileResponse*
-(NSURLSessionTask*) chatProfileWithChatRequest: (AGChatRequest*) chatRequest
    completionHandler: (void (^)(AGResultChatProfileResponse* output, NSError* error)) handler;


/// 发起多模态诊断请求(流式返回)
/// 以 SSE 方式流式返回模型输出；单模型为真流式，多模型为伪流式。
///
/// @param chatRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGSseEmitter*
-(NSURLSessionTask*) chatStreamWithChatRequest: (AGChatRequest*) chatRequest
    completionHandler: (void (^)(AGSseEmitter* output, NSError* error)) handler;


/// 完成分片上传
/// 所有分片上传完成后，调用此接口合并分片并返回最终的文件URL。
///
/// @param multipartUploadCompleteRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultString*
-(NSURLSessionTask*) completeMultipartUploadWithMultipartUploadCompleteRequest: (AGMultipartUploadCompleteRequest*) multipartUploadCompleteRequest
    completionHandler: (void (^)(AGResultString* output, NSError* error)) handler;


/// 添加新记录的作物
/// 
///
/// @param myCropCreateRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultMyCropResponseDto*
-(NSURLSessionTask*) createCropWithMyCropCreateRequest: (AGMyCropCreateRequest*) myCropCreateRequest
    completionHandler: (void (^)(AGResultMyCropResponseDto* output, NSError* error)) handler;


/// 发布新帖子
/// 
///
/// @param postCreateRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPostResponseDto*
-(NSURLSessionTask*) createPostWithPostCreateRequest: (AGPostCreateRequest*) postCreateRequest
    completionHandler: (void (^)(AGResultPostResponseDto* output, NSError* error)) handler;


/// 管理员创建用户
/// 
///
/// @param adminUserUpdateDto 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) createUserWithAdminUserUpdateDto: (AGAdminUserUpdateDto*) adminUserUpdateDto
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;


/// 管理员删除评论
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) deleteCommentWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 删除作物
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) deleteCropWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 删除当前用户的识别历史记录
/// 根据历史记录 ID 删除当前登录用户自己的识别历史记录
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) deleteHistoryWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 管理员删除帖子
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) deletePostWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 管理员删除用户
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) deleteUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 收藏指定帖子
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) favoritePostWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 关注用户
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) followUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 获取当前用户的预警消息列表 (首页专用，仅未读)
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @5)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultMessageResponseDto*
-(NSURLSessionTask*) getAlertMessagesWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultMessageResponseDto* output, NSError* error)) handler;


/// 获取所有评论列表 (分页)
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultCommentResponseDto*
-(NSURLSessionTask*) getAllCommentsWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultCommentResponseDto* output, NSError* error)) handler;


/// 获取所有帖子列表 (分页)
/// 
///
/// @param tag  (optional)
/// @param q  (optional)
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultPostResponseDto*
-(NSURLSessionTask*) getAllPostsWithTag: (NSString*) tag
    q: (NSString*) q
    page: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultPostResponseDto* output, NSError* error)) handler;


/// 获取帖子评论列表
/// 
///
/// @param _id 
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultCommentResponseDto*
-(NSURLSessionTask*) getCommentsWithId: (NSNumber*) _id
    page: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultCommentResponseDto* output, NSError* error)) handler;


/// 获取作物详情 (包含种植日历记录)
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultMyCropResponseDto*
-(NSURLSessionTask*) getCropDetailWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultMyCropResponseDto* output, NSError* error)) handler;


/// 获取当前用户资料
/// 
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultUserProfileDto*
-(NSURLSessionTask*) getCurrentUserProfileWithCompletionHandler: 
    (void (^)(AGResultUserProfileDto* output, NSError* error)) handler;


/// 获取我收藏的帖子列表
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultPostResponseDto*
-(NSURLSessionTask*) getFavoritedPostsWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultPostResponseDto* output, NSError* error)) handler;


/// 获取当前用户的识别历史记录
/// 获取当前登录用户以往调用 Agent 的历史记录，按时间倒序排列
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultListAgentChatHistory*
-(NSURLSessionTask*) getHistoryWithCompletionHandler: 
    (void (^)(AGResultListAgentChatHistory* output, NSError* error)) handler;


/// 获取消息发布历史记录
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultAdminMessage*
-(NSURLSessionTask*) getMessageHistoryWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultAdminMessage* output, NSError* error)) handler;


/// 获取我的作物列表
/// 
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultListMyCropResponseDto*
-(NSURLSessionTask*) getMyCropsWithCompletionHandler: 
    (void (^)(AGResultListMyCropResponseDto* output, NSError* error)) handler;


/// 获取消息列表 (分页)
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultMessageGroupResponseDto*
-(NSURLSessionTask*) getMyMessagesWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultMessageGroupResponseDto* output, NSError* error)) handler;


/// 获取我发布的帖子列表
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultPostResponseDto*
-(NSURLSessionTask*) getMyPostsWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultPostResponseDto* output, NSError* error)) handler;


/// 获取指定帖子详情
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPostResponseDto*
-(NSURLSessionTask*) getPostDetailWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultPostResponseDto* output, NSError* error)) handler;


/// 获取帖子列表
/// 支持按标签过滤、关键字搜索和分页
///
/// @param tag  (optional)
/// @param q  (optional)
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultPostResponseDto*
-(NSURLSessionTask*) getPostsWithTag: (NSString*) tag
    q: (NSString*) q
    page: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultPostResponseDto* output, NSError* error)) handler;


/// 实时获取搜索建议词
/// 用于搜索框输入时的实时下拉列表
///
/// @param q 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultListString*
-(NSURLSessionTask*) getSuggestionsWithQ: (NSString*) q
    completionHandler: (void (^)(AGResultListString* output, NSError* error)) handler;


/// 获取热门标签列表
/// 
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultListTagDto*
-(NSURLSessionTask*) getTopTagsWithCompletionHandler: 
    (void (^)(AGResultListTagDto* output, NSError* error)) handler;


/// 获取未读消息数
/// 
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultLong*
-(NSURLSessionTask*) getUnreadCountWithCompletionHandler: 
    (void (^)(AGResultLong* output, NSError* error)) handler;


/// 获取指定用户详情
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) getUserByIdWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;


/// 获取用户列表 (分页)
/// 
///
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPageResultAdminUserResponseDto*
-(NSURLSessionTask*) getUsersWithPage: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultPageResultAdminUserResponseDto* output, NSError* error)) handler;


/// 健康检查
/// 
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultString*
-(NSURLSessionTask*) healthWithCompletionHandler: 
    (void (^)(AGResultString* output, NSError* error)) handler;


/// 给指定帖子点赞
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) likePostWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 用户登录
/// 使用用户名或手机号加上密码进行登录，成功后返回 JWT Token
///
/// @param loginRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) loginWithLoginRequest: (AGLoginRequest*) loginRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 手机号验证码登录
/// 使用手机号和验证码进行登录，如果手机号未注册将自动注册
///
/// @param smsLoginRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) loginBySmsWithSmsLoginRequest: (AGSmsLoginRequest*) smsLoginRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 一键已读所有消息
/// 
///
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) markAllAsReadWithCompletionHandler: 
    (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 标记单条消息为已读
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) markAsReadWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 发布新消息 (全员或定向预警)
/// 
///
/// @param adminMessageCreateRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) publishMessageWithAdminMessageCreateRequest: (AGAdminMessageCreateRequest*) adminMessageCreateRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 刷新 Token
/// 使用有效的 Refresh Token 获取新的 Access Token
///
/// @param refreshTokenRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAuthResponse*
-(NSURLSessionTask*) refreshWithRefreshTokenRequest: (AGRefreshTokenRequest*) refreshTokenRequest
    completionHandler: (void (^)(AGResultAuthResponse* output, NSError* error)) handler;


/// 取消/删除种植标签
/// 
///
/// @param _id 
/// @param tagOperationRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) removeTagWithId: (NSNumber*) _id
    tagOperationRequest: (AGTagOperationRequest*) tagOperationRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 重发历史消息
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) resendMessageWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 高级模糊搜索帖子
/// 返回匹配结果、推荐内容及关键词建议
///
/// @param q 
/// @param page  (optional) (default to @0)
/// @param size  (optional) (default to @10)
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultSearchResultResponse*
-(NSURLSessionTask*) searchPostsWithQ: (NSString*) q
    page: (NSNumber*) page
    size: (NSNumber*) size
    completionHandler: (void (^)(AGResultSearchResultResponse* output, NSError* error)) handler;


/// 发送短信验证码
/// 使用阿里云短信认证服务发送验证码（如果未配置AK，则使用模拟发送并在控制台打印）
///
/// @param sendSmsRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) sendSmsCodeWithSendSmsRequest: (AGSendSmsRequest*) sendSmsRequest
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 初始化分片上传(断点续传)
/// 根据文件Hash检查上传进度，返回未上传分片的预签名URL。注意：MinIO/S3要求除了最后一个分片外，其他每个分片必须 >= 5MB。
///
/// @param multipartUploadInitRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultMultipartUploadInitResponse*
-(NSURLSessionTask*) startMultipartUploadWithMultipartUploadInitRequest: (AGMultipartUploadInitRequest*) multipartUploadInitRequest
    completionHandler: (void (^)(AGResultMultipartUploadInitResponse* output, NSError* error)) handler;


/// 取消收藏
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) unfavoritePostWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 取消关注用户
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) unfollowUserWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 取消点赞
/// 
///
/// @param _id 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) unlikePostWithId: (NSNumber*) _id
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 管理员修改评论内容
/// 
///
/// @param _id 
/// @param commentRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultCommentResponseDto*
-(NSURLSessionTask*) updateCommentWithId: (NSNumber*) _id
    commentRequest: (AGCommentRequest*) commentRequest
    completionHandler: (void (^)(AGResultCommentResponseDto* output, NSError* error)) handler;


/// 修改作物基本信息
/// 
///
/// @param _id 
/// @param myCropUpdateRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultMyCropResponseDto*
-(NSURLSessionTask*) updateCropWithId: (NSNumber*) _id
    myCropUpdateRequest: (AGMyCropUpdateRequest*) myCropUpdateRequest
    completionHandler: (void (^)(AGResultMyCropResponseDto* output, NSError* error)) handler;


/// 修改登录密码
/// 修改成功后当前Token将立即失效，需重新登录
///
/// @param varNewPassword 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultVoid*
-(NSURLSessionTask*) updatePasswordWithVarNewPassword: (NSString*) varNewPassword
    completionHandler: (void (^)(AGResultVoid* output, NSError* error)) handler;


/// 管理员修改帖子内容
/// 
///
/// @param _id 
/// @param postCreateRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultPostResponseDto*
-(NSURLSessionTask*) updatePostWithId: (NSNumber*) _id
    postCreateRequest: (AGPostCreateRequest*) postCreateRequest
    completionHandler: (void (^)(AGResultPostResponseDto* output, NSError* error)) handler;


/// 更新当前用户资料
/// 支持部分更新，字段为空则不修改
///
/// @param profileUpdateRequest 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultUserProfileDto*
-(NSURLSessionTask*) updateProfileWithProfileUpdateRequest: (AGProfileUpdateRequest*) profileUpdateRequest
    completionHandler: (void (^)(AGResultUserProfileDto* output, NSError* error)) handler;


/// 管理员更新用户
/// 
///
/// @param _id 
/// @param adminUserUpdateDto 
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultAdminUserResponseDto*
-(NSURLSessionTask*) updateUserWithId: (NSNumber*) _id
    adminUserUpdateDto: (AGAdminUserUpdateDto*) adminUserUpdateDto
    completionHandler: (void (^)(AGResultAdminUserResponseDto* output, NSError* error)) handler;


/// 通用单文件上传
/// 上传单张图片/文件至对象存储，并返回可公开访问的 URL。
///
/// @param file 
/// @param prefix  (optional) (default to @"uploads/")
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultString*
-(NSURLSessionTask*) uploadFileWithFile: (NSURL*) file
    prefix: (NSString*) prefix
    completionHandler: (void (^)(AGResultString* output, NSError* error)) handler;


/// 通用多文件批量上传
/// 一次性上传多张图片/文件，返回按顺序排列的 URL 列表。
///
/// @param files 
/// @param prefix  (optional) (default to @"uploads/")
/// 
///  code:400 message:"Bad Request",
///  code:500 message:"Internal Server Error",
///  code:200 message:"OK"
///
/// @return AGResultListString*
-(NSURLSessionTask*) uploadFilesWithFiles: (NSArray<NSURL*>*) files
    prefix: (NSString*) prefix
    completionHandler: (void (^)(AGResultListString* output, NSError* error)) handler;



@end
