#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGAuthResponse
@end

@interface AGAuthResponse : AGObject

/* JWT Token [optional]
 */
@property(nonatomic) NSString* token;
/* Refresh Token (用于刷新短效Token) [optional]
 */
@property(nonatomic) NSString* refreshToken;
/* Token 过期时间戳 (秒级) [optional]
 */
@property(nonatomic) NSNumber* expiresIn;
/* 用户ID [optional]
 */
@property(nonatomic) NSNumber* userId;
/* 用户名 [optional]
 */
@property(nonatomic) NSString* username;
/* 用户昵称/展示名 [optional]
 */
@property(nonatomic) NSString* fullName;
/* 随机生成的默认密码（仅在验证码登录且自动注册成功时返回） [optional]
 */
@property(nonatomic) NSString* generatedPassword;

@end
