#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGChatRequest
@end

@interface AGChatRequest : AGObject

/* 用户的提问文本 [optional]
 */
@property(nonatomic) NSString* text;
/* 图片的 Base64 字符串或公开的 HTTP URL [optional]
 */
@property(nonatomic) NSString* imageUrl;
/* 指定是否使用单模型方案（传给底层的多模态消息），默认为系统配置 [optional]
 */
@property(nonatomic) NSNumber* useSingleModel;
/* 预留的额外信息，如客户端的预处理结果，会一并提交给大模型作为上下文参考 [optional]
 */
@property(nonatomic) NSString* extraInfo;
/* 是否保存本次识别记录（需要登录）。不传默认保存；传 false 则本次不落历史 [optional]
 */
@property(nonatomic) NSNumber* saveHistory;

@end
