#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "AGProfile.h"
@protocol AGProfile;
@class AGProfile;



@protocol AGChatProfileResponse
@end

@interface AGChatProfileResponse : AGObject

/* 模型回答文本 [optional]
 */
@property(nonatomic) NSString* answer;

@property(nonatomic) AGProfile* profile;

@end
