#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGCommentResponseDto
@end

@interface AGCommentResponseDto : AGObject

/* 评论ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* 帖子ID [optional]
 */
@property(nonatomic) NSNumber* postId;
/* 内容 [optional]
 */
@property(nonatomic) NSString* content;
/* 作者ID [optional]
 */
@property(nonatomic) NSNumber* authorId;
/* 作者昵称/展示名 [optional]
 */
@property(nonatomic) NSString* authorName;
/* 作者用户名 [optional]
 */
@property(nonatomic) NSString* authorUsername;
/* 作者头像 [optional]
 */
@property(nonatomic) NSString* authorAvatar;
/* 创建时间 [optional]
 */
@property(nonatomic) NSDate* createdAt;

@end
