#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGCultivationRecordDto
@end

@interface AGCultivationRecordDto : AGObject

/* 记录ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* 打卡日期 [optional]
 */
@property(nonatomic) NSDate* recordDate;
/* 标签类型: WATERING(浇水), FERTILIZING(施肥), MEDICATION(用药), NOTE(笔记) [optional]
 */
@property(nonatomic) NSString* tagType;
/* 笔记内容或状态文案 [optional]
 */
@property(nonatomic) NSString* content;
/* 状态: 0-待处理, 1-已完成 [optional]
 */
@property(nonatomic) NSNumber* status;

@end
