#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGDiagnosisItem
@end

@interface AGDiagnosisItem : AGObject

/* 病害名称 [optional]
 */
@property(nonatomic) NSString* diseaseName;
/* 病虫害可信程度，0-100 [optional]
 */
@property(nonatomic) NSNumber* confidence;
/* 防治方案 [optional]
 */
@property(nonatomic) NSString* controlPlan;

@end
