#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGImageSizeDto
@end

@interface AGImageSizeDto : AGObject

/* 图片宽度（像素） [optional]
 */
@property(nonatomic) NSNumber* width;
/* 图片高度（像素） [optional]
 */
@property(nonatomic) NSNumber* height;

@end
