#import <Foundation/Foundation.h>
#import <AFNetworking/AFURLRequestSerialization.h>

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


@interface AGJSONRequestSerializer : AFJSONRequestSerializer
@end
