#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGMessageResponseDto
@end

@interface AGMessageResponseDto : AGObject

/* 消息ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* 消息类型：LIKE (点赞), COMMENT (评论), SYSTEM (系统), ALERT (预警) [optional]
 */
@property(nonatomic) NSString* type;
/* 消息标题 [optional]
 */
@property(nonatomic) NSString* title;
/* 消息内容 [optional]
 */
@property(nonatomic) NSString* content;
/* 发送者ID (系统消息或预警消息时可能为空) [optional]
 */
@property(nonatomic) NSNumber* senderId;
/* 发送者昵称/展示名 [optional]
 */
@property(nonatomic) NSString* senderName;
/* 发送者用户名 [optional]
 */
@property(nonatomic) NSString* senderUsername;
/* 发送者头像 [optional]
 */
@property(nonatomic) NSString* senderAvatar;
/* 关联的帖子ID [optional]
 */
@property(nonatomic) NSNumber* postId;
/* 是否已读 [optional]
 */
@property(nonatomic) NSNumber* isRead;
/* 接收时间 [optional]
 */
@property(nonatomic) NSDate* createdAt;

@end
