#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "AGPageResultMessageResponseDto.h"
@protocol AGPageResultMessageResponseDto;
@class AGPageResultMessageResponseDto;



@protocol AGMessageGroupResponseDto
@end

@interface AGMessageGroupResponseDto : AGObject


@property(nonatomic) AGPageResultMessageResponseDto* systemMessages;
/* 系统消息未读数 [optional]
 */
@property(nonatomic) NSNumber* systemUnreadCount;

@property(nonatomic) AGPageResultMessageResponseDto* alertMessages;
/* 预警消息未读数 [optional]
 */
@property(nonatomic) NSNumber* alertUnreadCount;

@property(nonatomic) AGPageResultMessageResponseDto* commentMessages;
/* 评论消息未读数 [optional]
 */
@property(nonatomic) NSNumber* commentUnreadCount;

@end
