#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGMultipartUploadInitResponse
@end

@interface AGMultipartUploadInitResponse : AGObject

/* 上传任务ID，后续合并和上传需要用到（当前实现为fileHash） [optional]
 */
@property(nonatomic) NSString* uploadId;
/* 已经上传成功的分片序号列表（断点续传用，从1开始） [optional]
 */
@property(nonatomic) NSArray<NSNumber*>* uploadedParts;
/* 需要上传的分片对应的预签名URL字典（Key为分片序号，Value为PUT请求的URL） [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* uploadUrls;

@end
