#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGMultipartUploadInitRequest
@end

@interface AGMultipartUploadInitRequest : AGObject

/* 文件的唯一Hash值（如MD5/SHA256），用于标识文件和断点续传 
 */
@property(nonatomic) NSString* fileHash;
/* 原始文件名 
 */
@property(nonatomic) NSString* filename;
/* 分片总数 
 */
@property(nonatomic) NSNumber* partCount;
/* 文件的ContentType，不传则自动推断 [optional]
 */
@property(nonatomic) NSString* contentType;

@end
