#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGMultipartUploadCompleteRequest
@end

@interface AGMultipartUploadCompleteRequest : AGObject

/* 上传任务ID 
 */
@property(nonatomic) NSString* uploadId;
/* 原始文件名 
 */
@property(nonatomic) NSString* filename;
/* 分片总数 
 */
@property(nonatomic) NSNumber* partCount;
/* 文件的ContentType [optional]
 */
@property(nonatomic) NSString* contentType;
/* 上传路径前缀 [optional]
 */
@property(nonatomic) NSString* prefix;

@end
