#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGMyCropUpdateRequest
@end

@interface AGMyCropUpdateRequest : AGObject

/* 植物名称 [optional]
 */
@property(nonatomic) NSString* plantName;
/* 植物图片URL [optional]
 */
@property(nonatomic) NSString* imageUrl;
/* 植物状态 [optional]
 */
@property(nonatomic) NSString* status;
/* 种植时间 [optional]
 */
@property(nonatomic) NSDate* plantingDate;
/* 预计成熟时间 [optional]
 */
@property(nonatomic) NSDate* maturityDate;
/* 病虫害次数 [optional]
 */
@property(nonatomic) NSNumber* pestCount;

@end
