#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "AGAdminMessage.h"
@protocol AGAdminMessage;
@class AGAdminMessage;



@protocol AGPageResultAdminMessage
@end

@interface AGPageResultAdminMessage : AGObject

/* 数据列表 [optional]
 */
@property(nonatomic) NSArray<AGAdminMessage>* list;
/* 当前页码 (从0开始) [optional]
 */
@property(nonatomic) NSNumber* page;
/* 每页大小 [optional]
 */
@property(nonatomic) NSNumber* size;
/* 总记录数 [optional]
 */
@property(nonatomic) NSNumber* total;
/* 总页数 [optional]
 */
@property(nonatomic) NSNumber* totalPages;
/* 是否还有下一页 [optional]
 */
@property(nonatomic) NSNumber* hasNext;

@end
