#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGPostResponseDto
@end

@interface AGPostResponseDto : AGObject

/* 帖子ID [optional]
 */
@property(nonatomic) NSNumber* _id;
/* 标题 [optional]
 */
@property(nonatomic) NSString* title;
/* 内容 [optional]
 */
@property(nonatomic) NSString* content;
/* 图片列表 [optional]
 */
@property(nonatomic) NSArray<NSString*>* images;
/* 标签列表 [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;
/* 作者ID [optional]
 */
@property(nonatomic) NSNumber* authorId;
/* 作者昵称/展示名 [optional]
 */
@property(nonatomic) NSString* authorName;
/* 作者用户名 [optional]
 */
@property(nonatomic) NSString* authorUsername;
/* 作者头像 [optional]
 */
@property(nonatomic) NSString* authorAvatar;
/* 点赞数 [optional]
 */
@property(nonatomic) NSNumber* likeCount;
/* 收藏数 [optional]
 */
@property(nonatomic) NSNumber* favoriteCount;
/* 评论数 [optional]
 */
@property(nonatomic) NSNumber* commentCount;
/* 当前用户是否已点赞 [optional]
 */
@property(nonatomic) NSNumber* isLiked;
/* 当前用户是否已收藏 [optional]
 */
@property(nonatomic) NSNumber* isFavorited;
/* 创建时间 [optional]
 */
@property(nonatomic) NSDate* createdAt;
/* 更新时间 [optional]
 */
@property(nonatomic) NSDate* updatedAt;

@end
