#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGPostCreateRequest
@end

@interface AGPostCreateRequest : AGObject

/* 帖子标题 
 */
@property(nonatomic) NSString* title;
/* 帖子内容 
 */
@property(nonatomic) NSString* content;
/* 帖子图片列表 [optional]
 */
@property(nonatomic) NSArray<NSString*>* images;
/* 关联的农作物标签列表 [optional]
 */
@property(nonatomic) NSArray<NSString*>* tags;

@end
