#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGProfile
@end

@interface AGProfile : AGObject

/* 本次请求唯一标识 [optional]
 */
@property(nonatomic) NSString* requestId;
/* 服务端解析到的客户端 IP [optional]
 */
@property(nonatomic) NSString* clientIp;
/* HTTP 请求体字节数（用于估算上传/传输开销） [optional]
 */
@property(nonatomic) NSNumber* requestBytes;
/* 是否包含图片输入 [optional]
 */
@property(nonatomic) NSNumber* hasImage;
/* imageUrl 字符串长度（base64 时通常很大） [optional]
 */
@property(nonatomic) NSNumber* imageUrlLength;
/* 图片输入类型：none/url/base64/unknown [optional]
 */
@property(nonatomic) NSString* imageUrlType;
/* extraInfo 字符串长度（用于估算上下文注入开销） [optional]
 */
@property(nonatomic) NSNumber* extraInfoLength;
/* 是否使用单模型方案（单模型：多模态直推；多模型：视觉识别+工具推导） [optional]
 */
@property(nonatomic) NSNumber* singleModel;
/* 获取用户 ID 耗时（毫秒） [optional]
 */
@property(nonatomic) NSNumber* getUserIdMs;
/* 清洗与规范化 imageUrl 耗时（毫秒） [optional]
 */
@property(nonatomic) NSNumber* normalizeImageUrlMs;
/* 视觉模型耗时（毫秒，仅多模型有图片时不为 0） [optional]
 */
@property(nonatomic) NSNumber* visionMs;
/* Agent/模型推理耗时（毫秒，含工具调用） [optional]
 */
@property(nonatomic) NSNumber* agentMs;
/* 保存历史记录耗时（毫秒） [optional]
 */
@property(nonatomic) NSNumber* saveHistoryMs;
/* 服务端总耗时（毫秒） [optional]
 */
@property(nonatomic) NSNumber* totalMs;

@end
