#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGRegisterRequest
@end

@interface AGRegisterRequest : AGObject

/* 用户名 (选填，不填则自动生成) [optional]
 */
@property(nonatomic) NSString* username;
/* 手机号 
 */
@property(nonatomic) NSString* phone;
/* 密码 
 */
@property(nonatomic) NSString* password;

@end
