#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGResultString
@end

@interface AGResultString : AGObject

/* 业务状态码 (200为成功) [optional]
 */
@property(nonatomic) NSNumber* code;
/* 响应消息说明 [optional]
 */
@property(nonatomic) NSString* message;
/* 响应数据体 [optional]
 */
@property(nonatomic) NSString* data;

@end
