#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "AGPageResultPostResponseDto.h"
#import "AGPostResponseDto.h"
@protocol AGPageResultPostResponseDto;
@class AGPageResultPostResponseDto;
@protocol AGPostResponseDto;
@class AGPostResponseDto;



@protocol AGSearchResultResponse
@end

@interface AGSearchResultResponse : AGObject


@property(nonatomic) AGPageResultPostResponseDto* matches;
/* 推荐的相关帖子列表 (基于算法或热度) [optional]
 */
@property(nonatomic) NSArray<AGPostResponseDto>* recommendations;
/* 建议的搜索关键词列表 (纠错或扩展) [optional]
 */
@property(nonatomic) NSArray<NSString*>* suggestions;

@end
