#import <Foundation/Foundation.h>
#import "AGObject.h"

/**
* Agri-Pest-Server API
* 农业病虫害识别 App 服务端 API 文档
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol AGTagOperationRequest
@end

@interface AGTagOperationRequest : AGObject

/* 打卡日期 [optional]
 */
@property(nonatomic) NSDate* recordDate;
/* 标签类型: WATERING, FERTILIZING, MEDICATION, NOTE [optional]
 */
@property(nonatomic) NSString* tagType;
/* 笔记内容或状态文案 (例如: 已浇水, 待浇水) [optional]
 */
@property(nonatomic) NSString* content;
/* 状态: 0-待处理, 1-已完成 [optional]
 */
@property(nonatomic) NSNumber* status;

@end
